language: node_js

node_js:
  - "8"

sudo: required

addons: chrome

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

